### ISSUE TITLE
Experiments in the paper

### ISSUE THREAD

**Issue by seermer** [foivospar/Arc2Face#10]
Hello, thank you so much for the great work! 
I noticed that there is not too much description of how experiments on previous works like InstantID are conducted. Would you mind sharing, were the InstantID experiments conducted using the publicly available SDXL version? Or were they based on the SD1.5 version? Were all methods compared under 512x512 resolution? Thank you.

**Comment by foivospar** [comment]
Hi, thanks for the interest. Yes, we used the publicly available SDXL model and the official [inference code](https://github.com/InstantID/InstantID#usage) from the InstantID repo. Yes, all methods in Tab. 1 were compared under the same resolution (512x512) after face detection and alignment (as mentioned in the paper).

**Comment by seermer** [comment]
Thank you so much for the quick reply!
