### ISSUE TITLE
Is it possible to use human pose guided controlnet with Arc2Face to generate full body human image?

### ISSUE THREAD

**Issue by silence-tang** [foivospar/Arc2Face#19]
Hi, this is a great work!
May I ask is it possible to use human pose guided controlnet with Arc2Face to generate full body human image?

**Comment by foivospar** [comment]
Hi! Our model is trained on aligned and cropped face images, so adding a pre-trained ControlNet for human poses will most likely lead to inconsistencies. Extending it to full-body generation would probably require further training (the model, the ControlNet, or both) on body data.

**Comment by silence-tang** [comment]
> Hi! Our model is trained on aligned and cropped face images, so adding a pre-trained ControlNet for human poses will most likely lead to inconsistencies. Extending it to full-body generation would probably require further training (the model, the ControlNet, or both) on body data.

Thanks for your answer!
