### ISSUE TITLE
assert 'detection' in self.models

### ISSUE THREAD

**Issue by lizhaohu** [foivospar/Arc2Face#21]
Here is the translation of your provided text into English:

I have confirmed that I have downloaded the arcface.onnx file you provided and that FaceAnalysis has located this file. However, when I print model.taskname, the output is model.taskname: recognition None. There is no detection key. Could you please tell me what's going on? My insightface version is 0.7.3.

**Comment by and86802** [comment]
same issue
Could you elaborate how you solve it?

**Comment by and86802** [comment]
I change the root into './antelopev2' and I solve it

**Comment by weathon** [comment]
Hi, how did you solved it
