### ISSUE TITLE
The issue when running app_controlnet.py

### ISSUE THREAD

**Issue by wweiGit** [foivospar/Arc2Face#38]
I couldn't find preprocess_for_emoca in external.emoca.gdl.datasets.ImageTestDataset, and it is also missing in the original emoca project. Additionally, I tried to offline generate 3D faces using emoca as cond_img, but the results were very poor. I would greatly appreciate it if you could help me resolve this issue.

**Comment by yangyuya** [comment]
I meet the same question. How do you resolve it ?
