### ISSUE TITLE
the output is unexpected

### ISSUE THREAD

**Issue by BlueWinters** [foivospar/Arc2Face#5]
thank you for you work.
but the output is unexpected.
I just try to run the demo code in README.md, input image: 'assets/examples/joacquin.png'

![0](https://github.com/foivospar/Arc2Face/assets/16732444/ba07e294-4f10-4255-a1ec-3875ba019597)
![1](https://github.com/foivospar/Arc2Face/assets/16732444/8db282fa-ac66-4bf5-8534-5ce5722f137e)

**Comment by foivospar** [comment]
You have to replace the insightface recognition model `glintr100.onnx` with our model `arcface.onnx` inside ./models/antelopev2. Please check our [instructions](https://github.com/foivospar/Arc2Face#download-models) on how to download `arcface.onnx` from our HuggingFace [repository](https://huggingface.co/FoivosPar/Arc2Face).
